#!/bin/sh
pip3 install virtualenv
virtualenv -p python3.6 /usr/lib/prismarine-server/venv
/usr/lib/prismarine-server/venv/bin/pip install -r /usr/lib/prismarine-server/requirements.txt
/usr/lib/prismarine-server/venv/bin/pip install gunicorn
ln -s /etc/nginx/sites-available/prismarine /etc/nginx/sites-enabled/prismarine
